repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.3.0
    hooks:
    -   id: gitleaks
-   repo: https://github.com/aquasecurity/tfsec
    rev: v1.4.2
    hooks:
    -   id: tfsec
-   repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
    -   id: hadolint
