name: gitleaks
on:
  pull_request:
    branches:
      - '!master'
concurrency:
  cancel-in-progress: true
permissions: read-all
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

