name: gitleaks
on:
  pull_request:
    branches:
      - '!master'
concurrency:
  cancel-in-progress: true
permissions: read-all
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@1f2d10fb689bc07a5f56f48d6db61f5bbbe772fa # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

