name: gitleaks
on:
  pull_request:
    branches:
      - '!master'
concurrency:
  cancel-in-progress: true
permissions: read-all
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

