name: docker build
on:
  pull_request:
    branches:
      - '!master'
    paths:
      - 'docker/**'
concurrency:
  cancel-in-progress: true
permissions: read-all

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2 
    - uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183 # v2.1.0
    with:
      dockerfile: Dockerfile

