name: tfsec-pr-commenter
on:
  pull_request:
    branches:
      - '!master'
    paths:
      - 'terraform/**'
concurrency:
  cancel-in-progress: true
permissions: read-all
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.5
        with:
          github_token: ${{ github.token }}

