name: build
on:
  pull_request:
    branches:
      - '!master'
    paths:
      - 'docker/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: read-all
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GHCR_SLUG: ghcr.io/${{ github.repository }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=pr
            type=edge
          labels: |
            org.opencontainers.image.title=something
            org.opencontainers.image.vendor=${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
        with:
          platforms: linux/amd64

      - name: Build OCI image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: docker
          outputs: type=oci,dest=oci.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca # 0.16.1
        with:
          input: /github/workspace/oci.tar
          severity: 'CRITICAL,HIGH'
